apiVersion: apps/v1
kind: Deployment
metadata:
  name: pongservice
  namespace: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: pong-service
        image: w00kyx/pong:v1
---
apiVersion: v1
kind: Service
metadata:
  name: pong-entrypoint
  namespace: pingpong
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30001
