version: "3.0"

services:
  ping:
    image: w00kyx/ping:v1
    environment:
       URL_PONG: "http://pong:8081/pong"
    depends_on:
      - pong
    ports:
      - "8080:8080"

  pong:
     image: w00kyx/pong:v1
